version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://orion:@localhost:5432/personality_db
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5000"
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: orion
      POSTGRES_PASSWORD:
      POSTGRES_DB: personality_db
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
